export const lessonStroke: Record<string, any> = {
  // HANGEUL 1 VOWELS
  // 아 group
  a: require("@/assets/buckets/lessonStroke/a.png"),
  e: require("@/assets/buckets/lessonStroke/e.png"),
  wu: require("@/assets/buckets/lessonStroke/wu.png"),
  o: require("@/assets/buckets/lessonStroke/o.png"),
  u: require("@/assets/buckets/lessonStroke/u.png"),
  i: require("@/assets/buckets/lessonStroke/i.png"),

  // 나 group
  na: require("@/assets/buckets/lessonStroke/na.png"),
  ne: require("@/assets/buckets/lessonStroke/ne.png"),
  nwu: require("@/assets/buckets/lessonStroke/nwu.png"),
  no: require("@/assets/buckets/lessonStroke/no.png"),
  nu: require("@/assets/buckets/lessonStroke/nu.png"),
  ni: require("@/assets/buckets/lessonStroke/ni.png"),

  // 라 group
  la: require("@/assets/buckets/lessonStroke/la.png"),
  le: require("@/assets/buckets/lessonStroke/le.png"),
  lwu: require("@/assets/buckets/lessonStroke/lwu.png"),
  lo: require("@/assets/buckets/lessonStroke/lo.png"),
  lu: require("@/assets/buckets/lessonStroke/lu.png"),
  li: require("@/assets/buckets/lessonStroke/li.png"),

  // 마 group
  ma: require("@/assets/buckets/lessonStroke/ma.png"),
  me: require("@/assets/buckets/lessonStroke/me.png"),
  mwu: require("@/assets/buckets/lessonStroke/mwu.png"),
  mo: require("@/assets/buckets/lessonStroke/mo.png"),
  mu: require("@/assets/buckets/lessonStroke/mu.png"),
  mi: require("@/assets/buckets/lessonStroke/mi.png"),

  // Practice
  namwu: require("@/assets/buckets/lessonStroke/namwu.png"),
  ai: require("@/assets/buckets/lessonStroke/ai.png"),
  oi: require("@/assets/buckets/lessonStroke/oi.png"),
  imo: require("@/assets/buckets/lessonStroke/imo.png"),
  ima: require("@/assets/buckets/lessonStroke/ima.png"),

  // HANGEUL 2 VOWELS
  // 아 group
  ya: require("@/assets/buckets/lessonStroke/ya.png"),
  ye: require("@/assets/buckets/lessonStroke/ye.png"),
  yo: require("@/assets/buckets/lessonStroke/yo.png"),
  yu: require("@/assets/buckets/lessonStroke/yu.png"),
  uy: require("@/assets/buckets/lessonStroke/uy.png"),

  //가 group
  ka: require("@/assets/buckets/lessonStroke/ka.png"),
  ke: require("@/assets/buckets/lessonStroke/ke.png"),
  ko: require("@/assets/buckets/lessonStroke/ko.png"),
  kwu: require("@/assets/buckets/lessonStroke/kwu.png"),
  ku: require("@/assets/buckets/lessonStroke/ku.png"),
  ki: require("@/assets/buckets/lessonStroke/ki.png"),

  //다 group
  ta: require("@/assets/buckets/lessonStroke/ta.png"),
  te: require("@/assets/buckets/lessonStroke/te.png"),
  to: require("@/assets/buckets/lessonStroke/to.png"),
  twu: require("@/assets/buckets/lessonStroke/twu.png"),
  tu: require("@/assets/buckets/lessonStroke/tu.png"),
  ti: require("@/assets/buckets/lessonStroke/ti.png"),

  // 바 group
  pa: require("@/assets/buckets/lessonStroke/pa.png"),
  pe: require("@/assets/buckets/lessonStroke/pe.png"),
  po: require("@/assets/buckets/lessonStroke/po.png"),
  pwu: require("@/assets/buckets/lessonStroke/pwu.png"),
  pu: require("@/assets/buckets/lessonStroke/pu.png"),
  pi: require("@/assets/buckets/lessonStroke/pi.png"),

  // 사 group
  sa: require("@/assets/buckets/lessonStroke/sa.png"),
  se: require("@/assets/buckets/lessonStroke/se.png"),
  so: require("@/assets/buckets/lessonStroke/so.png"),
  swu: require("@/assets/buckets/lessonStroke/swu.png"),
  su: require("@/assets/buckets/lessonStroke/su.png"),
  si: require("@/assets/buckets/lessonStroke/si.png"),

  // 자 group
  ca: require("@/assets/buckets/lessonStroke/ca.png"),
  ce: require("@/assets/buckets/lessonStroke/ce.png"),
  co: require("@/assets/buckets/lessonStroke/co.png"),
  cwu: require("@/assets/buckets/lessonStroke/cwu.png"),
  cu: require("@/assets/buckets/lessonStroke/cu.png"),
  ci: require("@/assets/buckets/lessonStroke/ci.png"),

  // finals group
  pam: require("@/assets/buckets/lessonStroke/pam.png"),
  pan: require("@/assets/buckets/lessonStroke/pan.png"),
  pal: require("@/assets/buckets/lessonStroke/pal.png"),
  pang: require("@/assets/buckets/lessonStroke/pang.png"),

  // Practice
  wuyu: require("@/assets/buckets/lessonStroke/wuyu.png"),
  yewu: require("@/assets/buckets/lessonStroke/yewu.png"),
  yoli: require("@/assets/buckets/lessonStroke/yoli.png"),
  yakwu: require("@/assets/buckets/lessonStroke/yakwu.png"),
  koki: require("@/assets/buckets/lessonStroke/koki.png"),
  kokwuma: require("@/assets/buckets/lessonStroke/kokwuma.png"),
  tali: require("@/assets/buckets/lessonStroke/tali.png"),
  kwutwu: require("@/assets/buckets/lessonStroke/kwutwu.png"),
  twuyu: require("@/assets/buckets/lessonStroke/twuyu.png"),
  latio: require("@/assets/buckets/lessonStroke/latio.png"),
  pata: require("@/assets/buckets/lessonStroke/pata.png"),
  napi: require("@/assets/buckets/lessonStroke/napi.png"),
  pinwu: require("@/assets/buckets/lessonStroke/pinwu.png"),
  uysa: require("@/assets/buckets/lessonStroke/uysa.png"),
  kaswu: require("@/assets/buckets/lessonStroke/kaswu.png"),
  pesu: require("@/assets/buckets/lessonStroke/pesu.png"),
  moca: require("@/assets/buckets/lessonStroke/moca.png"),
  uyca: require("@/assets/buckets/lessonStroke/uyca.png"),
  paci: require("@/assets/buckets/lessonStroke/paci.png"),
  apeci: require("@/assets/buckets/lessonStroke/apeci.png"),

  kam: require("@/assets/buckets/lessonStroke/kam.png"),
  san: require("@/assets/buckets/lessonStroke/san.png"),
  kyul: require("@/assets/buckets/lessonStroke/kyul.png"),
  yong: require("@/assets/buckets/lessonStroke/yong.png"),
  ay: require("@/assets/buckets/lessonStroke/ay.png"),
  ey: require("@/assets/buckets/lessonStroke/ey.png"),
  way: require("@/assets/buckets/lessonStroke/way.png"),
  wey: require("@/assets/buckets/lessonStroke/wey.png"),
  oy: require("@/assets/buckets/lessonStroke/oy.png"),
  kha: require("@/assets/buckets/lessonStroke/kha.png"),
  khe: require("@/assets/buckets/lessonStroke/khe.png"),
  kho: require("@/assets/buckets/lessonStroke/kho.png"),
  khwu: require("@/assets/buckets/lessonStroke/khwu.png"),
  khu: require("@/assets/buckets/lessonStroke/khu.png"),
  khi: require("@/assets/buckets/lessonStroke/khi.png"),
  tha: require("@/assets/buckets/lessonStroke/tha.png"),
  the: require("@/assets/buckets/lessonStroke/the.png"),
  tho: require("@/assets/buckets/lessonStroke/tho.png"),
  thwu: require("@/assets/buckets/lessonStroke/thwu.png"),
  thu: require("@/assets/buckets/lessonStroke/thu.png"),
  thi: require("@/assets/buckets/lessonStroke/thi.png"),
  pha: require("@/assets/buckets/lessonStroke/pha.png"),
  phe: require("@/assets/buckets/lessonStroke/phe.png"),
  pho: require("@/assets/buckets/lessonStroke/pho.png"),
  phwu: require("@/assets/buckets/lessonStroke/phwu.png"),
  phu: require("@/assets/buckets/lessonStroke/phu.png"),
  phi: require("@/assets/buckets/lessonStroke/phi.png"),
  cha: require("@/assets/buckets/lessonStroke/cha.png"),
  che: require("@/assets/buckets/lessonStroke/che.png"),
  cho: require("@/assets/buckets/lessonStroke/cho.png"),
  chwu: require("@/assets/buckets/lessonStroke/chwu.png"),
  chu: require("@/assets/buckets/lessonStroke/chu.png"),
  chi: require("@/assets/buckets/lessonStroke/chi.png"),
  ha: require("@/assets/buckets/lessonStroke/ha.png"),
  he: require("@/assets/buckets/lessonStroke/he.png"),
  ho: require("@/assets/buckets/lessonStroke/ho.png"),
  hwu: require("@/assets/buckets/lessonStroke/hwu.png"),
  hu: require("@/assets/buckets/lessonStroke/hu.png"),
  hi: require("@/assets/buckets/lessonStroke/hi.png"),
  kak: require("@/assets/buckets/lessonStroke/kak.png"),
  kap: require("@/assets/buckets/lessonStroke/kap.png"),
  kat: require("@/assets/buckets/lessonStroke/kat.png"),
  kas: require("@/assets/buckets/lessonStroke/kas.png"),
  kac: require("@/assets/buckets/lessonStroke/kac.png"),
  pay: require("@/assets/buckets/lessonStroke/pay.png"),
  kakey: require("@/assets/buckets/lessonStroke/kakey.png"),
  twayci: require("@/assets/buckets/lessonStroke/twayci.png"),
  weytingtuleysu: require("@/assets/buckets/lessonStroke/weytingtuleysu.png"),
  oynson: require("@/assets/buckets/lessonStroke/oynson.png"),
  khatu: require("@/assets/buckets/lessonStroke/khatu.png"),
  khameyla: require("@/assets/buckets/lessonStroke/khameyla.png"),
  sukhi: require("@/assets/buckets/lessonStroke/sukhi.png"),
  kheyikhu: require("@/assets/buckets/lessonStroke/kheyikhu.png"),
  khethun: require("@/assets/buckets/lessonStroke/khethun.png"),
  sathang: require("@/assets/buckets/lessonStroke/sathang.png"),
  theynisu: require("@/assets/buckets/lessonStroke/theynisu.png"),
  theylleypicen: require("@/assets/buckets/lessonStroke/theylleypicen.png"),
  thomatho: require("@/assets/buckets/lessonStroke/thomatho.png"),
  sukheyithu: require("@/assets/buckets/lessonStroke/sukheyithu.png"),
  phal: require("@/assets/buckets/lessonStroke/phal.png"),
  polpheyn: require("@/assets/buckets/lessonStroke/polpheyn.png"),
  phica: require("@/assets/buckets/lessonStroke/phica.png"),
  khephi: require("@/assets/buckets/lessonStroke/khephi.png"),
  yenphil: require("@/assets/buckets/lessonStroke/yenphil.png"),
  phwutul: require("@/assets/buckets/lessonStroke/phwutul.png"),
  kicha: require("@/assets/buckets/lessonStroke/kicha.png"),
  catongcha: require("@/assets/buckets/lessonStroke/catongcha.png"),
  chima: require("@/assets/buckets/lessonStroke/chima.png"),
  chinkwu: require("@/assets/buckets/lessonStroke/chinkwu.png"),
  chil: require("@/assets/buckets/lessonStroke/chil.png"),
  konghang: require("@/assets/buckets/lessonStroke/konghang.png"),
  hayntuphon: require("@/assets/buckets/lessonStroke/hayntuphon.png"),
  pihayngki: require("@/assets/buckets/lessonStroke/pihayngki.png"),
  heli: require("@/assets/buckets/lessonStroke/heli.png"),
  hyuci: require("@/assets/buckets/lessonStroke/hyuci.png"),
  hwuchwu: require("@/assets/buckets/lessonStroke/hwuchwu.png"),
  chayk: require("@/assets/buckets/lessonStroke/chayk.png"),
  cip: require("@/assets/buckets/lessonStroke/cip.png"),
  kot: require("@/assets/buckets/lessonStroke/kot.png"),
  os: require("@/assets/buckets/lessonStroke/os.png"),
  nac: require("@/assets/buckets/lessonStroke/nac.png"),
  thayksi: require("@/assets/buckets/lessonStroke/thayksi.png"),
  pokswunga: require("@/assets/buckets/lessonStroke/pokswunga.png"),
  kimpap: require("@/assets/buckets/lessonStroke/kimpap.png"),
  swutkalak: require("@/assets/buckets/lessonStroke/swutkalak.png"),
  ceskalak: require("@/assets/buckets/lessonStroke/ceskalak.png"),
  cesso: require("@/assets/buckets/lessonStroke/cesso.png"),
  chokhollis: require("@/assets/buckets/lessonStroke/chokhollis.png"),

  // hangeul 4
  yay: require("@/assets/buckets/lessonStroke/yay.png"),
  yey: require("@/assets/buckets/lessonStroke/yey.png"),
  wa: require("@/assets/buckets/lessonStroke/wa.png"),
  we: require("@/assets/buckets/lessonStroke/we.png"),
  wi: require("@/assets/buckets/lessonStroke/wi.png"),
  kka: require("@/assets/buckets/lessonStroke/kka.png"),
  kke: require("@/assets/buckets/lessonStroke/kke.png"),
  kko: require("@/assets/buckets/lessonStroke/kko.png"),
  kkwu: require("@/assets/buckets/lessonStroke/kkwu.png"),
  kku: require("@/assets/buckets/lessonStroke/kku.png"),
  kki: require("@/assets/buckets/lessonStroke/kki.png"),
  tta: require("@/assets/buckets/lessonStroke/tta.png"),
  tte: require("@/assets/buckets/lessonStroke/tte.png"),
  tto: require("@/assets/buckets/lessonStroke/tto.png"),
  ttwu: require("@/assets/buckets/lessonStroke/ttwu.png"),
  ttu: require("@/assets/buckets/lessonStroke/ttu.png"),
  tti: require("@/assets/buckets/lessonStroke/tti.png"),
  ppa: require("@/assets/buckets/lessonStroke/ppa.png"),
  ppe: require("@/assets/buckets/lessonStroke/ppe.png"),
  ppo: require("@/assets/buckets/lessonStroke/ppo.png"),
  ppwu: require("@/assets/buckets/lessonStroke/ppwu.png"),
  ppu: require("@/assets/buckets/lessonStroke/ppu.png"),
  ppi: require("@/assets/buckets/lessonStroke/ppi.png"),
  ssa: require("@/assets/buckets/lessonStroke/ssa.png"),
  sse: require("@/assets/buckets/lessonStroke/sse.png"),
  sso: require("@/assets/buckets/lessonStroke/sso.png"),
  sswu: require("@/assets/buckets/lessonStroke/sswu.png"),
  ssu: require("@/assets/buckets/lessonStroke/ssu.png"),
  ssi: require("@/assets/buckets/lessonStroke/ssi.png"),
  cca: require("@/assets/buckets/lessonStroke/cca.png"),
  cce: require("@/assets/buckets/lessonStroke/cce.png"),
  cco: require("@/assets/buckets/lessonStroke/cco.png"),
  ccwu: require("@/assets/buckets/lessonStroke/ccwu.png"),
  ccu: require("@/assets/buckets/lessonStroke/ccu.png"),
  cci: require("@/assets/buckets/lessonStroke/cci.png"),
  kakh: require("@/assets/buckets/lessonStroke/kakh.png"),
  kaph: require("@/assets/buckets/lessonStroke/kaph.png"),
  kath: require("@/assets/buckets/lessonStroke/kath.png"),
  kach: require("@/assets/buckets/lessonStroke/kach.png"),
  kah: require("@/assets/buckets/lessonStroke/kah.png"),
  yayki: require("@/assets/buckets/lessonStroke/yayki.png"),
  sikyey: require("@/assets/buckets/lessonStroke/sikyey.png"),
  hwacangsil: require("@/assets/buckets/lessonStroke/hwacangsil.png"),
  teweyo: require("@/assets/buckets/lessonStroke/teweyo.png"),
  kawi: require("@/assets/buckets/lessonStroke/kawi.png"),
  kkamansayk: require("@/assets/buckets/lessonStroke/kkamansayk.png"),
  ekkay: require("@/assets/buckets/lessonStroke/ekkay.png"),
  kkwul: require("@/assets/buckets/lessonStroke/kkwul.png"),
  kkwum: require("@/assets/buckets/lessonStroke/kkwum.png"),
  thokki: require("@/assets/buckets/lessonStroke/thokki.png"),
  ttalki: require("@/assets/buckets/lessonStroke/ttalki.png"),
  ttek: require("@/assets/buckets/lessonStroke/ttek.png"),
  ttokttok: require("@/assets/buckets/lessonStroke/ttokttok.png"),
  ttwukkeng: require("@/assets/buckets/lessonStroke/ttwukkeng.png"),
  ttukeweyo: require("@/assets/buckets/lessonStroke/ttukeweyo.png"),
  pappayo: require("@/assets/buckets/lessonStroke/pappayo.png"),
  ppaltay: require("@/assets/buckets/lessonStroke/ppaltay.png"),
  ppalkansayk: require("@/assets/buckets/lessonStroke/ppalkansayk.png"),
  ppang: require("@/assets/buckets/lessonStroke/ppang.png"),
  yeyppeyo: require("@/assets/buckets/lessonStroke/yeyppeyo.png"),
  ssayo: require("@/assets/buckets/lessonStroke/ssayo.png"),
  pissayo: require("@/assets/buckets/lessonStroke/pissayo.png"),
  sseyo: require("@/assets/buckets/lessonStroke/sseyo.png"),
  ssuleykithong: require("@/assets/buckets/lessonStroke/ssuleykithong.png"),
  nalssi: require("@/assets/buckets/lessonStroke/nalssi.png"),
  nalcca: require("@/assets/buckets/lessonStroke/nalcca.png"),
  olunccok: require("@/assets/buckets/lessonStroke/olunccok.png"),
  oynccok: require("@/assets/buckets/lessonStroke/oynccok.png"),
  phalcci: require("@/assets/buckets/lessonStroke/phalcci.png"),
  ccimcilpang: require("@/assets/buckets/lessonStroke/ccimcilpang.png"),
  khiukh: require("@/assets/buckets/lessonStroke/khiukh.png"),
  iph: require("@/assets/buckets/lessonStroke/iph.png"),
  soth: require("@/assets/buckets/lessonStroke/soth.png"),
  kkoch: require("@/assets/buckets/lessonStroke/kkoch.png"),
  hiuh: require("@/assets/buckets/lessonStroke/hiuh.png"),
  pwuekh: require("@/assets/buckets/lessonStroke/pwuekh.png"),
  mwuluph: require("@/assets/buckets/lessonStroke/mwuluph.png"),
  phathpingswu: require("@/assets/buckets/lessonStroke/phathpingswu.png"),
  swuchpwul: require("@/assets/buckets/lessonStroke/swuchpwul.png"),
};
