export const practiceImages: Record<string, any> = {
  i: require("@/assets/buckets/practiceImages/i.png"),
  ai: require("@/assets/buckets/practiceImages/ai.png"),
  ima: require("@/assets/buckets/practiceImages/ima.png"),
  namwu: require("@/assets/buckets/practiceImages/namwu.png"),
  oli: require("@/assets/buckets/practiceImages/oli.png"),
  meli: require("@/assets/buckets/practiceImages/meli.png"),
  emeni: require("@/assets/buckets/practiceImages/emeni.png"),
  imo: require("@/assets/buckets/practiceImages/imo.png"),
  oi: require("@/assets/buckets/practiceImages/oi.png"),
  o: require("@/assets/buckets/practiceImages/o.png"),

  // Hangeul 2
  wuyu: require("@/assets/buckets/practiceImages/wuyu.png"),
  yewu: require("@/assets/buckets/practiceImages/yewu.png"),
  yoli: require("@/assets/buckets/practiceImages/yoli.png"),
  kwu: require("@/assets/buckets/practiceImages/kwu.png"),
  yakwu: require("@/assets/buckets/practiceImages/yakwu.png"),
  koki: require("@/assets/buckets/practiceImages/koki.png"),
  kokwuma: require("@/assets/buckets/practiceImages/kokwuma.png"),
  tali: require("@/assets/buckets/practiceImages/tali.png"),
  kwutwu: require("@/assets/buckets/practiceImages/kwutwu.png"),
  twuyu: require("@/assets/buckets/practiceImages/twuyu.png"),
  latio: require("@/assets/buckets/practiceImages/latio.png"),
  pata: require("@/assets/buckets/practiceImages/pata.png"),
  pi: require("@/assets/buckets/practiceImages/pi.png"),
  napi: require("@/assets/buckets/practiceImages/napi.png"),
  pinwu: require("@/assets/buckets/practiceImages/pinwu.png"),
  sa: require("@/assets/buckets/practiceImages/sa.png"),
  moca: require("@/assets/buckets/practiceImages/moca.png"),
  uyca: require("@/assets/buckets/practiceImages/uyca.png"),
  paci: require("@/assets/buckets/practiceImages/paci.png"),
  apeci: require("@/assets/buckets/practiceImages/apeci.png"),
  kam: require("@/assets/buckets/practiceImages/kam.png"),
  san: require("@/assets/buckets/practiceImages/san.png"),
  kyul: require("@/assets/buckets/practiceImages/kyul.png"),
  yong: require("@/assets/buckets/practiceImages/yong.png"),
  kaswu: require("@/assets/buckets/practiceImages/kaswu.png"),
  pesu: require("@/assets/buckets/practiceImages/pesu.png"),
  uysa: require("@/assets/buckets/practiceImages/uysa.png"),
};
